#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/Wireguard > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Converter/Wire* > /dev/null 2>&1
echo "*****************************************"
echo "*         WireGuard VPN removed         *"
echo "*****************************************"
sleep 1
exit 0
