#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/Wireguard > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Components/Converter/Wire* > /dev/null 2>&1
echo "*****************************************"
echo "*              WireGuard VPN            *"
echo "*        is now being installed...      *"
echo "*****************************************"
exit 0
